name: Daily Crypto News Message

on:
  schedule:
    # Run daily at 9:00 AM HKT (1:00 AM UTC)
    - cron: "0 1 * * *"

  # Allow manual triggering for testing
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable debug logging"
        required: false
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install production dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-prod.txt

      - name: Send daily message
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python bot.py

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: bot-logs
          path: |
            *.log
            logs/
          retention-days: 7
